### PR TITLE
Language Server info added

### PR DESCRIPTION
**Pull request by andre2007**

### CODE REVIEW

**Comment by RUSshy** [comment]
in extension box i had to set ``d`` without the ``.``

**Comment by tekord** [comment]
Should I enable 'Use native Intellij code-completion service'? Without it nothing works. But if enabled then I got exception from DLS Support plugin:

```
Details: Current thread: Thread[ApplicationImpl pooled thread 18,4,Idea Thread Group] 1654340627
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1585037025

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1090)
	at com.intellij.openapi.editor.impl.view.EditorView.assertIsReadAccess(EditorView.java:599)
	at com.intellij.openapi.editor.impl.view.EditorView.logicalPositionToOffset(EditorView.java:160)
	at com.intellij.openapi.editor.impl.EditorImpl.logicalPositionToOffset(EditorImpl.java:2137)
	at com.github.gtache.lsp.utils.DocumentUtils$.logicalToLSPPos(DocumentUtils.scala:49)
	at com.github.gtache.lsp.editor.EditorEventManager.$anonfun$onTypeFormatting$1(EditorEventManager.scala:1426)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by andre2007** [comment]
@RUSshy you are right, will fix this

**Comment by andre2007** [comment]
@tekord I am pretty sure I have deactivated this flag, but have to check.

**Comment by tekord** [comment]
Does not work for me, LSP plugin is crashing everytime I use it with DLS.

**Comment by andre2007** [comment]
@tekord this field is deactivated in my settings (Use native Intellij code-completion service).

**Pull request merged**
